lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_extractors:
        cookie:
            enabled: true
            name: BEARER   # cookie name you want to read from

    set_cookies:
        BEARER:          # must match the name above
            lifetime: null        # defaults to token ttl
            samesite: lax
            path: /
            domain: null          # let Symfony decide
            secure: true          # HTTPS only
            httpOnly: true        # <â€“ important
            partitioned: false